### ISSUE TITLE
Search for words written into a textbox

### ISSUE THREAD

**Issue by NeatNit** [bam/edge-contextMenuSearch#21]
When I type into a text box (for example, this one right now), occasionally I want to look up a word to make sure it means what I think it means, or for various other reasons. The context menu search doesn't show up in text boxes though. Is this intentional?

**Comment by bam** [comment]
No, it's not intentional. I just didn't think about such case.
Extensions API has pretty narrow support in Edge (compared to FF and Chrome). Actually there are a few 'contexts' where context menu item will show. For now I used only 'selection' and 'link'. It's needed to be investigated whether it's possible to work with textarea or input box...
Thank you for feature request!
